[build]
  command = "npm run build"
  publish = "dist"

# ✅ Redirect all SPA routes (React Router) to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Proxy API calls to your backend server
# Replace with your actual backend URL (include https://)
[[redirects]]
  from = "/api/*"
  to = "https://expense-tracker-4-ov1b.onrender.com/api"
  status = 200
  force = true
